on:
  schedule:
    - cron: '30 4 * * 1'
  push:
    branches: master

name: layerupdate


jobs:
  layerupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        
      - name: Install dep and create issue
        run: |
          install.packages(c("curl","httr", "projmgr"), type = "binary")
          source("create_issue.R")
        shell: Rscript {0}
        
      - name: commit current date file
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add "record_hydat_date.txt"
            git commit -m 'update date file'
          fi
