on:
  schedule:
    - cron: '00 22 * * 5'

name: layerupdate


jobs:
  layerupdate:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install dep and create issue
        run: |
          install.packages(c("curl","httr", "projmgr"))
          source("create_issue.R")
        shell: Rscript {0}

      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: commit current date file
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add "record_hydat_date.txt"
            git commit -m 'update date file'
            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
          fi
