on:
  schedule:
    - cron: '30 4 * * 1'
  push:
    branches: master

name: layerupdate


jobs:
  layerupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages(c("httr", "projmgr"))
        shell: Rscript {0}
      - name: Create issue
        run: |
          source("R/create_issue.R")
        shell: Rscript {0}
      - name: commit current date file
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add "record_hydat_date.txt"
            git commit -m 'update date file'
          fi
