on:
  push:
    branches: master

name: layerupdate


jobs:
  layerupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies/functions
        run: |
          install.packages(c("httr"))
          source("R/functions.R")
        shell: Rscript {0}
      
      - name: Set vars
        run: echo "foo1"
        env:
           NEED_UPDATE: TRUE
      
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
